<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\InvoiceFlow.Application\InvoiceFlow.Application.csproj" />
    <ProjectReference Include="..\..\src\InvoiceFlow.Domain\InvoiceFlow.Domain.csproj" />
  </ItemGroup>

</Project>
