using InvoiceFlow.Application.Invoices.Abstractions;
using InvoiceFlow.Application.Invoices.Dtos;
using InvoiceFlow.Application.Invoices.Requests;
using InvoiceFlow.Domain.Invoices;

namespace InvoiceFlow.Application.Invoices;

public sealed class InvoiceService(IInvoiceRepository invoiceRepository, TimeProvider? timeProvider = null)
{
    private readonly IInvoiceRepository _invoiceRepository =
        invoiceRepository ?? throw new ArgumentNullException(nameof(invoiceRepository));
    private readonly TimeProvider _timeProvider = timeProvider ?? TimeProvider.System;

    public async Task<string> ReserveInvoiceNumberAsync(CancellationToken cancellationToken = default)
    {
        while (true)
        {
            var sequence = await _invoiceRepository.ReserveInvoiceSequenceAsync(cancellationToken);
            var candidate = $"INV-{_timeProvider.GetLocalNow():yyyy}-{sequence:D6}";
            if (!await _invoiceRepository.InvoiceNumberExistsAsync(candidate, cancellationToken))
            {
                return candidate;
            }
        }
    }

    public Task<InvoiceListResultDto> GetInvoicesAsync(
        InvoiceListQuery query, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(query);
        return _invoiceRepository.GetPageAsync(query, cancellationToken);
    }

    public async Task<InvoiceDetailsDto?> GetInvoiceAsync(
        Guid id,
        CancellationToken cancellationToken = default)
    {
        var invoice = await _invoiceRepository.GetByIdAsync(id, cancellationToken);

        return invoice is null ? null : MapDetails(invoice);
    }

    public async Task<InvoiceDetailsDto> CreateInvoiceAsync(
        CreateInvoiceRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);

        var lineItemInputs = SnapshotLineItems(request.LineItems);

        if (lineItemInputs.Any(input => input.Id.HasValue))
        {
            throw new ArgumentException(
                "Line item IDs must not be supplied when creating an invoice.",
                nameof(request));
        }

        var number = request.InvoiceNumber is null
            ? await ReserveInvoiceNumberAsync(cancellationToken)
            : request.InvoiceNumber;
        for (var attempt = 0; ; attempt++)
        {
            var invoice = new Invoice(
                Guid.NewGuid(), number, request.CustomerName, request.IssueDate, request.CurrencyCode);
            foreach (var input in lineItemInputs)
            {
                invoice.AddLineItem(Guid.NewGuid(), input.Description, input.Quantity,
                    input.UnitPrice, input.DiscountPercent);
            }

            var details = MapDetails(invoice);

            try
            {
                await _invoiceRepository.AddAsync(invoice, cancellationToken);
                return details;
            }
            catch (Exceptions.DuplicateInvoiceNumberException) when (
                attempt < 3 && (request.AutoGeneratedNumber || request.InvoiceNumber is null))
            {
                number = await ReserveInvoiceNumberAsync(cancellationToken);
            }
        }
    }

    public async Task<bool> UpdateInvoiceAsync(
        Guid id,
        UpdateInvoiceRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);

        var lineItemInputs = SnapshotLineItems(request.LineItems);
        return await _invoiceRepository.UpdateAsync(id, invoice =>
        {
            var proposedState = BuildValidatedProposedState(invoice, request, lineItemInputs);
            ApplyProposedState(invoice, proposedState);
        }, cancellationToken);
    }

    public async Task<bool> DeleteInvoiceAsync(
        Guid id,
        CancellationToken cancellationToken = default)
    {
        return await _invoiceRepository.DeleteAsync(id, cancellationToken);
    }

    private static Invoice BuildValidatedProposedState(
        Invoice existingInvoice,
        UpdateInvoiceRequest request,
        IReadOnlyList<InvoiceLineItemInput> lineItemInputs)
    {
        ValidateExistingLineItemIds(existingInvoice, lineItemInputs);

        var proposedState = new Invoice(
            existingInvoice.Id,
            existingInvoice.InvoiceNumber,
            request.CustomerName,
            request.IssueDate,
            request.CurrencyCode);

        foreach (var input in lineItemInputs)
        {
            proposedState.AddLineItem(
                input.Id ?? Guid.NewGuid(),
                input.Description,
                input.Quantity,
                input.UnitPrice,
                input.DiscountPercent);
        }

        proposedState.CalculateTotals();

        return proposedState;
    }

    private static void ValidateExistingLineItemIds(
        Invoice invoice,
        IReadOnlyList<InvoiceLineItemInput> lineItemInputs)
    {
        var existingIds = invoice.LineItems.Select(lineItem => lineItem.Id).ToHashSet();
        var suppliedIds = new HashSet<Guid>();

        foreach (var input in lineItemInputs.Where(input => input.Id.HasValue))
        {
            var suppliedId = input.Id!.Value;

            if (!suppliedIds.Add(suppliedId))
            {
                throw new ArgumentException(
                    $"Line item ID '{suppliedId}' was supplied more than once.",
                    nameof(lineItemInputs));
            }

            if (!existingIds.Contains(suppliedId))
            {
                throw new ArgumentException(
                    $"Line item ID '{suppliedId}' does not belong to invoice '{invoice.Id}'.",
                    nameof(lineItemInputs));
            }
        }
    }

    private static void ApplyProposedState(Invoice invoice, Invoice proposedState)
    {
        invoice.UpdateDetails(
            proposedState.CustomerName,
            proposedState.IssueDate,
            proposedState.CurrencyCode);

        var requestedIds = proposedState.LineItems
            .Select(lineItem => lineItem.Id)
            .ToHashSet();

        foreach (var existingLineItem in invoice.LineItems
                     .Where(lineItem => !requestedIds.Contains(lineItem.Id))
                     .ToArray())
        {
            invoice.RemoveLineItem(existingLineItem.Id);
        }

        foreach (var requestedLineItem in proposedState.LineItems)
        {
            var existingLineItem = invoice.LineItems
                .SingleOrDefault(lineItem => lineItem.Id == requestedLineItem.Id);

            if (existingLineItem is null)
            {
                invoice.AddLineItem(
                    requestedLineItem.Id,
                    requestedLineItem.Description,
                    requestedLineItem.Quantity,
                    requestedLineItem.UnitPrice,
                    requestedLineItem.DiscountPercent);

                continue;
            }

            existingLineItem.UpdateDetails(
                requestedLineItem.Description,
                requestedLineItem.Quantity,
                requestedLineItem.UnitPrice,
                requestedLineItem.DiscountPercent);
        }
    }

    private static InvoiceLineItemInput[] SnapshotLineItems(
        IReadOnlyList<InvoiceLineItemInput> lineItems)
    {
        ArgumentNullException.ThrowIfNull(lineItems);

        return [.. lineItems];
    }

    private static InvoiceDetailsDto MapDetails(Invoice invoice)
    {
        var totals = invoice.CalculateTotals();
        return new(
            invoice.Id,
            invoice.InvoiceNumber,
            invoice.CustomerName,
            invoice.IssueDate,
            invoice.CurrencyCode,
            invoice.LineItems.Select(MapLineItem).ToArray(),
            totals.Subtotal,
            totals.TotalDiscount,
            totals.GrandTotal);
    }

    private static InvoiceLineItemDto MapLineItem(InvoiceLineItem lineItem) =>
        new(
            lineItem.Id,
            lineItem.Description,
            lineItem.Quantity,
            lineItem.UnitPrice,
            lineItem.DiscountPercent,
            lineItem.CalculateGrossAmount(),
            lineItem.CalculateDiscountAmount(),
            lineItem.CalculateLineTotal());
}
